[tool.poetry]
name = "polus-images-utils-midrc-download"
version = "0.1.0"
description = "An awesome function."
authors = [" Hamdah Shafqat Abbasi <hamdahshafqat.abbasi@nih.gov>"]
readme = "README.md"
packages = [{include = "polus", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
gen3 = "^4.22.4"
PyYAML = "^6.0.1"
pandas = "^2.2.1"
pydicom = "^2.4.4"
filepattern = ">=2.0.4,<3.0"
preadator = "^0.4.0.dev2"
typer = "^0.7.0"

[tool.poetry.group.dev.dependencies]
bump2version = "^1.0.1"
pytest = "^7.4"
pytest-sugar = "^0.9.6"
pre-commit = "^3.2.1"
black = "^23.3.0"
mypy = "^1.1.1"
ruff = "^0.0.270"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]
