name: py39

dependencies:
 - matplotlib=3.5.3
 - matplotlib-inline=0.1.3
 - pandas==1.4.2
 - numpy==1.21.5
 - scikit-learn=1.0.2
 - scikit-image=0.18.2
 - seaborn=0.11.2
 - pip=22.0.4
 - pip:
   - vaex==4.9.0
   - bfio[all]==2.1.9
   - filepattern==1.4.7
   - preadator==0.2.0
   - opencv-python-headless==4.5.1.48
   - imageio==2.8.0
   - basicpy==1.0.0
   - jaxlib
   - jax==0.3.15
   - torch==1.12.1
   - albumentations==1.1.0
   - tensorboard==2.8.0
   - git+https://github.com/PolusAI/segmentation_models.pytorch.git