name: seg

dependencies:
 - matplotlib=3.5.1
 - matplotlib-inline=0.1.3
 - pandas==1.4.1
 - numpy==1.21.5
 - scikit-learn=1.0.2
 - scikit-image=0.18.2
 - seaborn=0.11.2
 - pip=22.0.4
 - pip:
   - plotnine==0.8.0
   - lightgbm==3.3.2
   - pytorch-tabnet==3.1.1
   - xgboost==1.5.2
   - vaex==4.9.0
   - bfio[zarr]==2.1.9
   - filepattern==1.4.7
   - albumentations==1.1.0
   - tensorboard==2.8.0
   - git+https://github.com/PolusAI/segmentation_models.pytorch.git
